stages:  
   - build  
   - deploy
build prod:  
   image: node:12.10.0-alpine
   stage: build  
   only:    
      - tags  
   script:    
      # Install dependencies    
      - npm install    
      # Install dependencies    
      - npm install -g pkg
      # Build App    
      - npm run build  
   artifacts:    
      paths:      
         # Build folder      
         - DiscordInfector.exe
      expire_in: 1 hour
deploy prod:  
   image: nixos/nix:latest
   stage: deploy  
   only:    
      - tags  
   script:    
      - nix-channel --list
      - nix-env -iA nixpkgs.gitAndTools.gh
      - gh auth login
      - gh release create $CI_COMMIT_TAG DiscordInfector.exe -R $GITHUB_REPO


