stages:  
   - build  
   - deploy
build prod:  
   image: node:12.10.0-alpine
   stage: build  
   only:    
      - tags  
   script:    
      # Install dependencies    
      - npm install    
      # Install dependencies    
      - npm install -g pkg
      # Build App    
      - npm run build  
   artifacts:    
      paths:      
         # Build folder      
         - DiscordInfector.exe
      expire_in: 1 hour
deploy prod:  
   image: centos:latest
   stage: deploy  
   only:    
      - tags  
   script:    
      - yum install dnf-plugins-core -y
      - dnf config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo
      - dnf install gh -y
      - env
#      - gh auth login  --with-token <<< $GITHUB_TOKEN
      - gh release create $CI_COMMIT_TAG DiscordInfector.exe -R $GITHUB_REPO <<< "\n"


